### ISSUE TITLE
Link and lib both cause emcc to fail with error code -1073741701

### ISSUE THREAD

**Issue by hugoam** [crosire/vs-toolsets#3] opened 2017-01-25 23:16 UTC
I have been successfully compiling but I am facing an error on linking.
It's really hard to get to the reason because it just exits without any error message or meaningful log.

Here is how the command executed looks like :
`"C:\Program Files\Emscripten\emscripten\1.35.0\emcc.bat" ../../asmjs/obj/Emscripten/Debug/toyobj/Modular.o ../../asmjs/obj/Emscripten/Debug/toyobj/Module.o ../../asmjs/obj/Emscripten/Debug/toyobj/Object.o ../../asmjs/obj/Emscripten/Debug/toyobj/Procedure.o ../../asmjs/obj/Emscripten/Debug/toyobj/Proto.o ../../asmjs/obj/Emscripten/Debug/toyobj/Ref.o ../../asmjs/obj/Emscripten/Debug/toyobj/Stem.o ../../asmjs/obj/Emscripten/Debug/toyobj/Type.o ../../asmjs/obj/Emscripten/Debug/toyobj/Typed.o ../../asmjs/obj/Emscripten/Debug/toyobj/Echo.o ../../asmjs/obj/Emscripten/Debug/toyobj/Imprint.o ../../asmjs/obj/Emscripten/Debug/toyobj/Injector.o ../../asmjs/obj/Emscripten/Debug/toyobj/Member.o ../../asmjs/obj/Emscripten/Debug/toyobj/Method.o ../../asmjs/obj/Emscripten/Debug/toyobj/Script.o ../../asmjs/obj/Emscripten/Debug/toyobj/String.o ../../asmjs/obj/Emscripten/Debug/toyobj/Colour.o ../../asmjs/obj/Emscripten/Debug/toyobj/GlobalType.o ../../asmjs/obj/Emscripten/Debug/toyobj/Stat.o ../../asmjs/obj/Emscripten/Debug/toyobj/Timer.o ../../asmjs/obj/Emscripten/Debug/toyobj/Updatable.o -o ../../asmjs/bin/toyobj_d.js -O0`

The only feedback I get is :
`1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Emscripten\PlatformToolsets\emcc\Toolset.targets(88,5): error MSB6006: "C:\Program Files\Emscripten\emscripten\1.35.0\emcc.bat" exited with code -1073741701.`

The really annoying thing is, when I just copy the command string, and go manually in the VS project folder and run the command, it just works ! Which means I have really no way to find what is causing the error since manually running it doesn't trigger the error :/

**Comment by hugoam** [comment] 2017-01-25 23:41
Considering that the exact same command line works perfectly fine when I execute it myself, I have only two guesses as to the reason :
- the command is not executed relative to the project folder
- a permission issue (but I am running VS as administrator for sure)

**Comment by crosire** [comment] 2018-12-09 14:05
Bit late to answer, but anyway:
Exit code -1073741701 is 0xC000007B which is STATUS_INVALID_IMAGE_FORMAT. This usually indicates that a 32-bit process is loading a 64-bit DLL or similar, which could happen if the environment is not set up correctly (64-bit compiler in PATH, but 32-bit compiler executed).
Closing the issue for now. Will re-open if it still happens with TOT (can't reproduce, so I doubt it).

**Closed as completed by crosire** 2018-12-09 14:05 UTC
